### ISSUE TITLE
Accepting rules for refactoring pest code?

### ISSUE THREAD

**Issue by olivernybroe** [rectorphp/rector-pest#2]
Love to see a pest extension for rector 😍 

Would you accept rectors for refactoring pest code also or only phpunit to pest converter so far? 👀 

E.g. the current rule also converts `$this->assertSame(150, $result);` to `expect($result)->toBe(150);`, but would love to have that as a standalone rule as `$this->assertSame(150, $result);` is actually valid pest code also, but I don't want people to do that in our codebase.

**Comment by TomasVotruba** [comment]
Hi, glad you like it :+1:  
But please don't tell anybody, it's very fresh :D 

> Would you accept rectors for refactoring pest code also or only phpunit to pest converter so far? eyes

That would be perfect, I'd also learn more about Pest from such rules.
